set nocompatible

" ---- neovim settings
let g:is_kornshell=1
set clipboard=unnamedplus
set ffs=unix,dos,mac
set hidden
set mat=2
set mouse=a
set nofoldenable
set noswapfile
set number
set showmatch
set smartindent
set termguicolors
set whichwrap+=<,>,h,l
set wrap

" tabs
set expandtab
set shiftwidth=4
set softtabstop=-1
set tabstop=4

" ---- plugin settings
let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled=1
let g:vim_markdown_folding_disabled=1

" ---- plugins
call plug#begin()
" basic functionality
Plug 'flazz/vim-colorschemes'
Plug 'godlygeek/tabular', { 'on': ['Tab', 'Tabularize'] }
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
" languages
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries', 'for': 'go' }
Plug 'sheerun/vim-polyglot'
" fancy shit
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'airblade/vim-gitgutter'
Plug 'junegunn/goyo.vim', { 'for': 'markdown' }
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'vim-airline/vim-airline'
call plug#end()

" ---- custom mappings
set pastetoggle=<F2> " toggle paste mode

" gt to re-align text based on previous pattern
noremap gt :Tabularize<CR>

" :Sprunge to upload current buffer to sprunge.us
command! Sprunge w !curl -F 'sprunge=<-' http://sprunge.us

" F12 to reparse syntax
noremap <F12> <Esc>:syntax sync fromstart<CR>
inoremap <F12> <C-o>:syntax sync fromstart<CR>

" ---- finalize
if has('nvim')
    set rtp^=/usr/share/vim/vimfiles/ " let neovim piggy back off of vim packages
endif

color pencil
