#!/bin/sh
: ${XDG_OPT:=~/.local}
: ${XDG_CONFIG_HOME:=$XDG_OPT/etc}
: ${XDG_DATA_HOME:=$XDG_OPT/share}
: ${XDG_STATE_HOME:=$XDG_OPT/var}
: ${XDG_CACHE_HOME:=$XDG_OPT/tmp}
export XDG_CONFIG_HOME XDG_DATA_HOME XDG_STATE_HOME XDG_CACHE_HOME

# convenience
xdgopt="$XDG_HOME" xdgetc="$XDG_CONFIG_HOME" xdgshr="$XDG_DATA_HOME" xdgvar="$XDG_STATE_HOME"  xdgtmp="$XDG_CACHE_HOME"

# XDG compatiblity settings for everything
export BUN_INSTALL="$xdgopt"/bun

export CLJ_CACHE="$xdgtmp"/clojure CLJ_CONFIG="$xdgetc"/clojure

export DOTNET_CLI_HOME="$xdgopt"/dotnet

export ELAN_HOME="$xdgopt"/elan

export JULIA_DEPOT_PATH="$xdgopt"/julia JULIAUP_DEPOT_PATH="$xdgopt"/julia

export OPAMROOT="$xdgopt"/ocaml

export IPYTHONDIR="$xdgopt"/python/ipython JUPYTER_CONFIG_DIR="$xdgopt"/python/jupyter
export UV_PYTHON_BIN_DIR="$xdgopt"/python/bin UV_PYTHON_INSTALL_DIR="$xdgopt"/python/interpreters UV_TOOL_BIN_DIR="$xdgopt"/python/bin UV_TOOL_DIR="$xdgopt"/python/tools

export CARGO_HOME="$xdgopt"/rust RUSTUP_HOME="$xdgopt"/rust

export ZVM_PATH="$xdgopt"/zig

export RLWRAP_HOME="$xdgvar"/history
export LESSHISTFILE=$RLWRAP_HOME/less
export NODE_REPL_HISTORY=$RLWRAP_HOME/node
export PSQL_HISTORY=$RLWRAP_HOME/psql
export PYTHON_HISTORY=$RLWRAP_HOME/python
export SQLITE_HISTORY=$RLWRAP_HOME/sqlite
export USQL_HISTORY=$RLWRAP_HOME/usql
