#!/bin/sh
: ${XDG_CONFIG_HOME:=~/.local/etc}
: ${XDG_DATA_HOME:=~/.local/share}
: ${XDG_STATE_HOME:=~/.local/var}
: ${XDG_CACHE_HOME:=~/.local/tmp}
export XDG_CONFIG_HOME XDG_DATA_HOME XDG_STATE_HOME XDG_CACHE_HOME

# convenience
xdgetc="$XDG_CONFIG_HOME" xdgshr="$XDG_DATA_HOME" xdgvar="$XDG_STATE_HOME"  xdgtmp="$XDG_CACHE_HOME"

# XDG compatiblity settings for everything
export BUN_INSTALL=~/.local/bun

export CLJ_CACHE="$xdgtmp"/clojure CLJ_CONFIG="$xdgetc"/clojure

export DOTNET_CLI_HOME=~/.local/dotnet

export ELAN_HOME=~/.local/elan

export JULIA_DEPOT_PATH=~/.local/julia JULIAUP_DEPOT_PATH=~/.local/julia

export OPAMROOT=~/.local/ocaml

export IPYTHONDIR=~/.local/python/ipython JUPYTER_CONFIG_DIR=~/.local/python/jupyter
export UV_PYTHON_BIN_DIR=~/.local/python/bin UV_PYTHON_INSTALL_DIR=~/.local/python/interpreters UV_TOOL_BIN_DIR=~/.local/python/bin UV_TOOL_DIR=~/.local/python/tools

export CARGO_HOME=~/.local/rust RUSTUP_HOME=~/.local/rust

export ZVM_PATH=~/.local/zig

export RLWRAP_HOME="$xdgvar"/history
export LESSHISTFILE=$RLWRAP_HOME/less
export NODE_REPL_HISTORY=$RLWRAP_HOME/node
export PSQL_HISTORY=$RLWRAP_HOME/psql
export PYTHON_HISTORY=$RLWRAP_HOME/python
export SQLITE_HISTORY=$RLWRAP_HOME/sqlite
export USQL_HISTORY=$RLWRAP_HOME/usql
