# -*- mode: sh -*-
# vim: ft=zsh
xzsource zprofile.pre

: ${PAGER:=less} ${EDITOR:=vi} \
  ${HOSTNAME:=$(uname -n)} ${USER:=$(id -un)} \
  ${HISTFILE:=~/.local/state/history/zsh}
if [ "${HISTSIZE:-30}" = 30 ]; then
	HISTSIZE=5000
	SAVEHIST=10000
fi
export EDITOR HISTFILE PAGER

setopt nullglob
path=(~/bin ~/.local/share/sh ~/.local/*/bin /opt/*/bin {/usr,}{/local,}/{s,}bin)

xsource ~/.local/share/sh/xdg

xzsource zprofile.{local,post}
