# vim: ft=zsh
: ${ZDOTDIR:=~/.config/zsh}

xsource() {
	local i
	for i; do
		[ -r "$i" ] && source "$i"
	done
}
xzsource() {
	xsource "${@/#/$ZDOTDIR/}"
}

xzsource zshenv.pre

fpath[1,0]=($ZDOTDIR/functions)

xzsource zshenv.{local,post}
