#!/bin/zsh
(( $+commands[exa] )) || return

# removes default ls-likes, replaces them with exa variants
unalias ls ll l la

# old ones
alias ls=exa ll='ls -l' l=ll la='l -a'
# extras
alias lr='l -T'
alias lp='lr --git-ignore'
